channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.9
  - numba=0.45.1
  - numpy=1.16.5
  - numpy-base=1.16.5
  - scikit-image=0.15.0
  - scipy=1.3.1
  - opencv=3.4.2
  - py-opencv=3.4.2
  - tqdm=4.32.1
